package com.model;

public enum Preparation {
    PETS_INSIDE,
    PET_FOOD,
    PET_CARRIER,
    CLOSE_WINDOWS,
    DOORS_LOCKED,
    FLASHLIGHT,
    WATER,
    CANNED_GOODS,
    DIAPERS,
    FORMULA,
    TOILET_PAPER,
    FIRST_AID_KIT,
    MEDICATIONS,
    MEDICAL_EQUIPMENT,
    EVACUATION_PLAN,
    CHARGED_DEVICES,
    DOCUMENTS_LOCATED
}